/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.io.*;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author SOLUTIONS
 */
public class TicTacToeFrame extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToeFrame
     */
    Font FONT_ZORQUE;

    public TicTacToeFrame() {
        setUndecorated(true);
        setAlwaysOnTop(true);
        setVisible(true);
        setResizable(false);
        int width = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int height = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        setSize(width, height);

        initComponents();
        try {
            InputStream is = new BufferedInputStream(getClass().getResourceAsStream("resources/zorque.ttf"));
            FONT_ZORQUE = Font.createFont(Font.TRUETYPE_FONT, is);
            LabelLogo.setFont(FONT_ZORQUE.deriveFont(144f));
            LabelUsername.setFont(FONT_ZORQUE.deriveFont(60f));
            LabelPassword.setFont(FONT_ZORQUE.deriveFont(60f));
            ButtonLogin.setFont(FONT_ZORQUE.deriveFont(72f));
            ButtonSignup.setFont(FONT_ZORQUE.deriveFont(72f));
            ButtonExit.setFont(FONT_ZORQUE.deriveFont(72f));
            ButtonExit.setOpaque(false);
            ButtonExit.setContentAreaFilled(false);
            ButtonExit.setBorderPainted(false);
            ButtonLogin.setOpaque(false);
            ButtonLogin.setContentAreaFilled(false);
            ButtonLogin.setBorderPainted(false);
            ButtonSignup.setOpaque(false);
            ButtonSignup.setContentAreaFilled(false);
            ButtonSignup.setBorderPainted(false);
            TextFieldUsername.setFont(FONT_ZORQUE.deriveFont(32f));
            PasswordFieldPassword.setFont(FONT_ZORQUE.deriveFont(32f));
            TextFieldUsername.requestFocus();

            LabelLogo2.setFont(FONT_ZORQUE.deriveFont(144f));
            ButtonStartGame.setFont(FONT_ZORQUE.deriveFont(72f));
            ButtonRecords.setFont(FONT_ZORQUE.deriveFont(72f));
            ButtonQuit.setFont(FONT_ZORQUE.deriveFont(72f));
            ButtonStartGame.setOpaque(false);
            ButtonStartGame.setContentAreaFilled(false);
            ButtonStartGame.setBorderPainted(false);
            ButtonRecords.setOpaque(false);
            ButtonRecords.setContentAreaFilled(false);
            ButtonRecords.setBorderPainted(false);
            ButtonQuit.setOpaque(false);
            ButtonQuit.setContentAreaFilled(false);
            ButtonQuit.setBorderPainted(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        LabelUsername = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        TextFieldUsername = new javax.swing.JTextField();
        ButtonLogin = new javax.swing.JButton();
        ButtonSignup = new javax.swing.JButton();
        PasswordFieldPassword = new javax.swing.JPasswordField();
        ButtonExit = new javax.swing.JButton();
        MainMenuPanel = new javax.swing.JPanel();
        LabelLogo2 = new javax.swing.JLabel();
        ButtonStartGame = new javax.swing.JButton();
        ButtonRecords = new javax.swing.JButton();
        ButtonQuit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parentPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(33, 33, 33));
        loginPanel.setFocusable(false);
        loginPanel.setNextFocusableComponent(TextFieldUsername);

        LabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        LabelLogo.setForeground(new java.awt.Color(158, 158, 158));
        LabelLogo.setText("TicTacToe");

        LabelUsername.setForeground(new java.awt.Color(158, 158, 158));
        LabelUsername.setText("Username");

        LabelPassword.setForeground(new java.awt.Color(158, 158, 158));
        LabelPassword.setText("Passowrd");

        TextFieldUsername.setBackground(new java.awt.Color(158, 158, 158));
        TextFieldUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        TextFieldUsername.setMinimumSize(new java.awt.Dimension(80, 50));
        TextFieldUsername.setNextFocusableComponent(PasswordFieldPassword);
        TextFieldUsername.setPreferredSize(new java.awt.Dimension(80, 50));
        TextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUsernameActionPerformed(evt);
            }
        });

        ButtonLogin.setForeground(new java.awt.Color(158, 158, 158));
        ButtonLogin.setText("Login");
        ButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonLoginMouseExited(evt);
            }
        });
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });

        ButtonSignup.setForeground(new java.awt.Color(158, 158, 158));
        ButtonSignup.setText("Signup");
        ButtonSignup.setToolTipText("Create a new account");
        ButtonSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonSignupMouseExited(evt);
            }
        });
        ButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignupActionPerformed(evt);
            }
        });

        PasswordFieldPassword.setBackground(new java.awt.Color(158, 158, 158));
        PasswordFieldPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        PasswordFieldPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PasswordFieldPassword.setMinimumSize(new java.awt.Dimension(80, 50));
        PasswordFieldPassword.setPreferredSize(new java.awt.Dimension(80, 50));

        ButtonExit.setForeground(new java.awt.Color(183, 28, 28));
        ButtonExit.setText("X");
        ButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonExitMouseExited(evt);
            }
        });
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(ButtonExit)
                        .addGap(50, 50, 50))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(ButtonLogin)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(ButtonSignup))
                            .addComponent(TextFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(374, Short.MAX_VALUE))))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelLogo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ButtonExit)
                .addGap(0, 0, 0)
                .addComponent(LabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(LabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLogin)
                    .addComponent(ButtonSignup))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        parentPanel.add(loginPanel, "card1");

        MainMenuPanel.setBackground(new java.awt.Color(33, 33, 33));

        LabelLogo2.setBackground(new java.awt.Color(255, 255, 153));
        LabelLogo2.setForeground(new java.awt.Color(158, 158, 158));
        LabelLogo2.setText("TicTacToe");

        ButtonStartGame.setForeground(new java.awt.Color(158, 158, 158));
        ButtonStartGame.setText("Start Game");
        ButtonStartGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonStartGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonStartGameMouseExited(evt);
            }
        });
        ButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartGameActionPerformed(evt);
            }
        });

        ButtonRecords.setForeground(new java.awt.Color(158, 158, 158));
        ButtonRecords.setText("Records");
        ButtonRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonRecordsMouseExited(evt);
            }
        });

        ButtonQuit.setForeground(new java.awt.Color(158, 158, 158));
        ButtonQuit.setText("Quit");
        ButtonQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonQuitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonQuitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MainMenuPanelLayout = new javax.swing.GroupLayout(MainMenuPanel);
        MainMenuPanel.setLayout(MainMenuPanelLayout);
        MainMenuPanelLayout.setHorizontalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelLogo2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonStartGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainMenuPanelLayout.setVerticalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(LabelLogo2)
                .addGap(69, 69, 69)
                .addComponent(ButtonStartGame)
                .addGap(64, 64, 64)
                .addComponent(ButtonRecords)
                .addGap(62, 62, 62)
                .addComponent(ButtonQuit)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        parentPanel.add(MainMenuPanel, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        parentPanel.add(jPanel1, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonStartGameActionPerformed

    private void ButtonStartGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonStartGameMouseEntered
        // TODO add your handling code here:
        ButtonStartGame.setForeground(new Color(224, 224, 224));
    }//GEN-LAST:event_ButtonStartGameMouseEntered

    private void ButtonStartGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonStartGameMouseExited
        // TODO add your handling code here:
        ButtonStartGame.setForeground(new Color(158, 158, 158));
    }//GEN-LAST:event_ButtonStartGameMouseExited

    private void ButtonRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRecordsMouseEntered
        // TODO add your handling code here:
        ButtonRecords.setForeground(new Color(224, 224, 224));
    }//GEN-LAST:event_ButtonRecordsMouseEntered

    private void ButtonRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRecordsMouseExited
        // TODO add your handling code here:
        ButtonRecords.setForeground(new Color(158, 158, 158));

    }//GEN-LAST:event_ButtonRecordsMouseExited

    private void ButtonQuitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonQuitMouseEntered
        // TODO add your handling code here:
        ButtonQuit.setForeground(new Color(224, 224, 224));

    }//GEN-LAST:event_ButtonQuitMouseEntered

    private void ButtonQuitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonQuitMouseExited
        // TODO add your handling code here:
        ButtonQuit.setForeground(new Color(158, 158, 158));

    }//GEN-LAST:event_ButtonQuitMouseExited

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonExitActionPerformed

    private void ButtonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseExited
        // TODO add your handling code here:
        ButtonExit.setForeground(new Color(183, 28, 28));
    }//GEN-LAST:event_ButtonExitMouseExited

    private void ButtonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseEntered
        // TODO add your handling code here:
        ButtonExit.setForeground(new Color(229, 57, 53));
    }//GEN-LAST:event_ButtonExitMouseEntered

    private void ButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignupActionPerformed
        parentPanel.removeAll();
        parentPanel.add(MainMenuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();         // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSignupActionPerformed

    private void ButtonSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSignupMouseExited
        // TODO add your handling code here:
        ButtonSignup.setForeground(new Color(158, 158, 158));
    }//GEN-LAST:event_ButtonSignupMouseExited

    private void ButtonSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSignupMouseEntered
        // TODO add your handling code here:
        ButtonSignup.setForeground(new Color(224, 224, 224));
    }//GEN-LAST:event_ButtonSignupMouseEntered

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        parentPanel.removeAll();
        parentPanel.add(MainMenuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void ButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLoginMouseExited
        // TODO add your handling code here:
        ButtonLogin.setForeground(new Color(158, 158, 158));
    }//GEN-LAST:event_ButtonLoginMouseExited

    private void ButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLoginMouseEntered
        // TODO add your handling code here:
        ButtonLogin.setForeground(new Color(224, 224, 224));
    }//GEN-LAST:event_ButtonLoginMouseEntered

    private void TextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JButton ButtonQuit;
    private javax.swing.JButton ButtonRecords;
    private javax.swing.JButton ButtonSignup;
    private javax.swing.JButton ButtonStartGame;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelLogo2;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JPanel MainMenuPanel;
    private javax.swing.JPasswordField PasswordFieldPassword;
    private javax.swing.JTextField TextFieldUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel parentPanel;
    // End of variables declaration//GEN-END:variables
}
